import { type Registry } from "shadcn/schema"

export const ui: Registry["items"] = [
  {
    name: "button",
    type: "registry:ui",
    files: [
      { path: "ui/button/button.variants.ts", type: "registry:ui" },
      { path: "ui/button/button.component.ts", type: "registry:ui" },
      { path: "ui/button/button.component.html", type: "registry:ui" },
      { path: "ui/button/index.ts", type: "registry:ui" },
    ],
    meta: {
      links: {
        docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/button",
      },
    },
  },
  {
    name: "badge",
    type: "registry:ui",
    files: [
      { path: "ui/badge/badge.variants.ts", type: "registry:ui" },
      { path: "ui/badge/badge.component.ts", type: "registry:ui" },
      { path: "ui/badge/badge.component.html", type: "registry:ui" },
      { path: "ui/badge/index.ts", type: "registry:ui" },
    ],
    meta: {
      links: {
        docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/badge",
      },
    },
  },
  {
    name: "card",
    type: "registry:ui",
    files: [
      { path: "ui/card/card.component.ts", type: "registry:ui" },
      { path: "ui/card/card.component.html", type: "registry:ui" },
      { path: "ui/card/index.ts", type: "registry:ui" },
    ],
    meta: {
      links: {
        docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/card",
      },
    },
  },
  {
    name: "separator",
    type: "registry:ui",
    files: [
      { path: "ui/separator/separator.component.ts", type: "registry:ui" },
      { path: "ui/separator/separator.component.html", type: "registry:ui" },
      { path: "ui/separator/index.ts", type: "registry:ui" },
    ],
    meta: {
      links: {
        docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/separator",
      },
    },
  },
  {
    name: "skeleton",
    type: "registry:ui",
    files: [
      { path: "ui/skeleton/skeleton.component.ts", type: "registry:ui" },
      { path: "ui/skeleton/skeleton.component.html", type: "registry:ui" },
      { path: "ui/skeleton/index.ts", type: "registry:ui" },
    ],
    meta: {
      links: {
        docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/skeleton",
      },
    },
  },
  {
    name: "label",
    type: "registry:ui",
    files: [
      { path: "ui/label/label.component.ts", type: "registry:ui" },
      { path: "ui/label/label.component.html", type: "registry:ui" },
      { path: "ui/label/index.ts", type: "registry:ui" },
    ],
    meta: {
      links: {
        docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/label",
      },
    },
  },
  {
    name: "kbd",
    type: "registry:ui",
    files: [
      { path: "ui/kbd/kbd.variants.ts", type: "registry:ui" },
      { path: "ui/kbd/kbd.component.ts", type: "registry:ui" },
      { path: "ui/kbd/kbd.component.html", type: "registry:ui" },
      { path: "ui/kbd/index.ts", type: "registry:ui" },
    ],
    meta: {
      links: {
        docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/kbd",
      },
    },
  },
  {
    name: "accordion",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/accordion/accordion.component.ts", type: "registry:ui" },
      { path: "ui/accordion/accordion-trigger.component.html", type: "registry:ui" },
      { path: "ui/accordion/accordion-content.component.html", type: "registry:ui" },
      { path: "ui/accordion/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/accordion" } },
  },
  {
    name: "checkbox",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/checkbox/checkbox.component.ts", type: "registry:ui" },
      { path: "ui/checkbox/checkbox.component.html", type: "registry:ui" },
      { path: "ui/checkbox/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/checkbox" } },
  },
  {
    name: "collapsible",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/collapsible/collapsible.component.ts", type: "registry:ui" },
      { path: "ui/collapsible/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/collapsible" } },
  },
  {
    name: "radio-group",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/radio-group/radio-group.component.ts", type: "registry:ui" },
      { path: "ui/radio-group/radio-group-item.component.html", type: "registry:ui" },
      { path: "ui/radio-group/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/radio-group" } },
  },
  {
    name: "switch",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/switch/switch.component.ts", type: "registry:ui" },
      { path: "ui/switch/switch.component.html", type: "registry:ui" },
      { path: "ui/switch/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/switch" } },
  },
  {
    name: "tabs",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/tabs/tabs.variants.ts", type: "registry:ui" },
      { path: "ui/tabs/tabs.component.ts", type: "registry:ui" },
      { path: "ui/tabs/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/tabs" } },
  },
  {
    name: "toggle",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/toggle/toggle.variants.ts", type: "registry:ui" },
      { path: "ui/toggle/toggle.component.ts", type: "registry:ui" },
      { path: "ui/toggle/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/toggle" } },
  },
  {
    name: "toggle-group",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    registryDependencies: ["toggle"],
    files: [
      { path: "ui/toggle-group/toggle-group.component.ts", type: "registry:ui" },
      { path: "ui/toggle-group/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/toggle-group" } },
  },
  {
    name: "alert",
    type: "registry:ui",
    files: [
      { path: "ui/alert/alert.variants.ts", type: "registry:ui" },
      { path: "ui/alert/alert.icons.ts", type: "registry:ui" },
      { path: "ui/alert/alert.component.ts", type: "registry:ui" },
      { path: "ui/alert/alert.component.html", type: "registry:ui" },
      { path: "ui/alert/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/alert" } },
  },
  {
    name: "avatar",
    type: "registry:ui",
    files: [
      { path: "ui/avatar/avatar.component.ts", type: "registry:ui" },
      { path: "ui/avatar/avatar-fallback.component.html", type: "registry:ui" },
      { path: "ui/avatar/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/avatar" } },
  },
  {
    name: "input",
    type: "registry:ui",
    files: [
      { path: "ui/input/input.variants.ts", type: "registry:ui" },
      { path: "ui/input/input.component.ts", type: "registry:ui" },
      { path: "ui/input/input.component.html", type: "registry:ui" },
      { path: "ui/input/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/input" } },
  },
  {
    name: "textarea",
    type: "registry:ui",
    files: [
      { path: "ui/textarea/textarea.variants.ts", type: "registry:ui" },
      { path: "ui/textarea/textarea.component.ts", type: "registry:ui" },
      { path: "ui/textarea/textarea.component.html", type: "registry:ui" },
      { path: "ui/textarea/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/textarea" } },
  },
  {
    name: "progress",
    type: "registry:ui",
    files: [
      { path: "ui/progress/progress.component.ts", type: "registry:ui" },
      { path: "ui/progress/progress.component.html", type: "registry:ui" },
      { path: "ui/progress/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/progress" } },
  },
  {
    name: "aspect-ratio",
    type: "registry:ui",
    files: [
      { path: "ui/aspect-ratio/aspect-ratio.component.ts", type: "registry:ui" },
      { path: "ui/aspect-ratio/aspect-ratio.component.html", type: "registry:ui" },
      { path: "ui/aspect-ratio/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/aspect-ratio" } },
  },
  {
    name: "empty",
    type: "registry:ui",
    files: [
      { path: "ui/empty/empty.variants.ts", type: "registry:ui" },
      { path: "ui/empty/empty.component.ts", type: "registry:ui" },
      { path: "ui/empty/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/empty" } },
  },
  {
    name: "spinner",
    type: "registry:ui",
    files: [
      { path: "ui/spinner/spinner.variants.ts", type: "registry:ui" },
      { path: "ui/spinner/spinner.component.ts", type: "registry:ui" },
      { path: "ui/spinner/spinner.component.html", type: "registry:ui" },
      { path: "ui/spinner/index.ts", type: "registry:ui" },
    ],
    meta: {
      links: {
        docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/spinner",
      },
    },
  },
  {
    name: "breadcrumb",
    type: "registry:ui",
    files: [
      { path: "ui/breadcrumb/breadcrumb.component.ts", type: "registry:ui" },
      { path: "ui/breadcrumb/breadcrumb-separator.component.html", type: "registry:ui" },
      { path: "ui/breadcrumb/breadcrumb-ellipsis.component.html", type: "registry:ui" },
      { path: "ui/breadcrumb/breadcrumb.component.html", type: "registry:ui" },
      { path: "ui/breadcrumb/breadcrumb.icons.ts", type: "registry:ui" },
      { path: "ui/breadcrumb/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/breadcrumb" } },
  },
  {
    name: "field",
    type: "registry:ui",
    registryDependencies: ["separator"],
    files: [
      { path: "ui/field/field.component.ts", type: "registry:ui" },
      { path: "ui/field/field.component.html", type: "registry:ui" },
      { path: "ui/field/field-separator.component.html", type: "registry:ui" },
      { path: "ui/field/field-error.component.html", type: "registry:ui" },
      { path: "ui/field/field.variants.ts", type: "registry:ui" },
      { path: "ui/field/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/field" } },
  },
  {
    name: "input-group",
    type: "registry:ui",
    registryDependencies: ["button", "input", "textarea"],
    files: [
      { path: "ui/input-group/input-group.variants.ts", type: "registry:ui" },
      { path: "ui/input-group/input-group-addon.variants.ts", type: "registry:ui" },
      { path: "ui/input-group/input-group-button.variants.ts", type: "registry:ui" },
      { path: "ui/input-group/input-group.component.ts", type: "registry:ui" },
      { path: "ui/input-group/input-group-addon.component.ts", type: "registry:ui" },
      { path: "ui/input-group/input-group-button.component.ts", type: "registry:ui" },
      { path: "ui/input-group/input-group-text.component.ts", type: "registry:ui" },
      { path: "ui/input-group/input-group-input.component.ts", type: "registry:ui" },
      { path: "ui/input-group/input-group-textarea.component.ts", type: "registry:ui" },
      { path: "ui/input-group/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/input-group" } },
  },
  {
    name: "item",
    type: "registry:ui",
    files: [
      { path: "ui/item/item.component.ts", type: "registry:ui" },
      { path: "ui/item/item-separator.component.html", type: "registry:ui" },
      { path: "ui/item/item.component.html", type: "registry:ui" },
      { path: "ui/item/item.variants.ts", type: "registry:ui" },
      { path: "ui/item/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/item" } },
  },
  {
    name: "button-group",
    type: "registry:ui",
    registryDependencies: ["button", "input", "textarea", "separator", "label"],
    files: [
      { path: "ui/button-group/button-group.component.ts", type: "registry:ui" },
      { path: "ui/button-group/button-group-separator.component.html", type: "registry:ui" },
      { path: "ui/button-group/button-group-text.component.html", type: "registry:ui" },
      { path: "ui/button-group/button-group.component.html", type: "registry:ui" },
      { path: "ui/button-group/button-group.variants.ts", type: "registry:ui" },
      { path: "ui/button-group/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/button-group" } },
  },
  {
    name: "input-otp",
    type: "registry:ui",
    files: [
      { path: "ui/input-otp/input-otp.component.ts", type: "registry:ui" },
      { path: "ui/input-otp/input-otp.component.html", type: "registry:ui" },
      { path: "ui/input-otp/input-otp-slot.component.ts", type: "registry:ui" },
      { path: "ui/input-otp/input-otp-slot.component.html", type: "registry:ui" },
      { path: "ui/input-otp/input-otp-group.component.ts", type: "registry:ui" },
      { path: "ui/input-otp/input-otp-group.component.html", type: "registry:ui" },
      { path: "ui/input-otp/input-otp-separator.component.ts", type: "registry:ui" },
      { path: "ui/input-otp/input-otp-separator.component.html", type: "registry:ui" },
      { path: "ui/input-otp/input-otp.icons.ts", type: "registry:ui" },
      { path: "ui/input-otp/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/input-otp" } },
  },
  {
    name: "slider",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/slider/slider.component.ts", type: "registry:ui" },
      { path: "ui/slider/slider.component.html", type: "registry:ui" },
      { path: "ui/slider/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/slider" } },
  },
  {
    name: "stepper",
    type: "registry:ui",
    files: [
      { path: "ui/stepper/stepper.component.ts", type: "registry:ui" },
      { path: "ui/stepper/stepper-indicator.component.html", type: "registry:ui" },
      { path: "ui/stepper/stepper.component.html", type: "registry:ui" },
      { path: "ui/stepper/stepper.variants.ts", type: "registry:ui" },
      { path: "ui/stepper/stepper.icons.ts", type: "registry:ui" },
      { path: "ui/stepper/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/stepper" } },
  },
  {
    name: "table",
    type: "registry:ui",
    files: [
      { path: "ui/table/table.component.ts", type: "registry:ui" },
      { path: "ui/table/table.component.html", type: "registry:ui" },
      { path: "ui/table/table.variants.ts", type: "registry:ui" },
      { path: "ui/table/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/table" } },
  },
  {
    name: "resizable",
    type: "registry:ui",
    files: [
      { path: "ui/resizable/resizable.component.ts", type: "registry:ui" },
      { path: "ui/resizable/resizable.component.html", type: "registry:ui" },
      { path: "ui/resizable/resizable.variants.ts", type: "registry:ui" },
      { path: "ui/resizable/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/resizable" } },
  },
  {
    name: "scroll-area",
    type: "registry:ui",
    files: [
      { path: "ui/scroll-area/scroll-area.component.ts", type: "registry:ui" },
      { path: "ui/scroll-area/scroll-area.component.html", type: "registry:ui" },
      { path: "ui/scroll-area/scroll-area.variants.ts", type: "registry:ui" },
      { path: "ui/scroll-area/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/scroll-area" } },
  },
  {
    name: "native-select",
    type: "registry:ui",
    files: [
      { path: "ui/native-select/native-select.component.ts", type: "registry:ui" },
      { path: "ui/native-select/native-select-wrapper.component.html", type: "registry:ui" },
      { path: "ui/native-select/native-select.component.html", type: "registry:ui" },
      { path: "ui/native-select/native-select.variants.ts", type: "registry:ui" },
      { path: "ui/native-select/native-select.icons.ts", type: "registry:ui" },
      { path: "ui/native-select/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/native-select" } },
  },
  {
    name: "dialog",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/dialog/dialog.component.ts", type: "registry:ui" },
      { path: "ui/dialog/dialog.component.html", type: "registry:ui" },
      { path: "ui/dialog/dialog.icons.ts", type: "registry:ui" },
      { path: "ui/dialog/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/dialog" } },
  },
  {
    name: "alert-dialog",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/alert-dialog/alert-dialog.component.ts", type: "registry:ui" },
      { path: "ui/alert-dialog/alert-dialog.component.html", type: "registry:ui" },
      { path: "ui/alert-dialog/alert-dialog.variants.ts", type: "registry:ui" },
      { path: "ui/alert-dialog/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/alert-dialog" } },
  },
  {
    name: "sheet",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/sheet/sheet.component.ts", type: "registry:ui" },
      { path: "ui/sheet/sheet.component.html", type: "registry:ui" },
      { path: "ui/sheet/sheet.variants.ts", type: "registry:ui" },
      { path: "ui/sheet/sheet.icons.ts", type: "registry:ui" },
      { path: "ui/sheet/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/sheet" } },
  },
  {
    name: "drawer",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/drawer/drawer.component.ts", type: "registry:ui" },
      { path: "ui/drawer/drawer.component.html", type: "registry:ui" },
      { path: "ui/drawer/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/drawer" } },
  },
  {
    name: "popover",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/popover/popover.component.ts", type: "registry:ui" },
      { path: "ui/popover/popover.component.html", type: "registry:ui" },
      { path: "ui/popover/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/popover" } },
  },
  {
    name: "tooltip",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/tooltip/tooltip.component.ts", type: "registry:ui" },
      { path: "ui/tooltip/tooltip.component.html", type: "registry:ui" },
      { path: "ui/tooltip/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/tooltip" } },
  },
  {
    name: "hover-card",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/hover-card/hover-card.component.ts", type: "registry:ui" },
      { path: "ui/hover-card/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/hover-card" } },
  },
  {
    name: "dropdown-menu",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/dropdown-menu/dropdown-menu.component.ts", type: "registry:ui" },
      { path: "ui/dropdown-menu/dropdown-menu.component.html", type: "registry:ui" },
      { path: "ui/dropdown-menu/dropdown-menu-selectable.component.ts", type: "registry:ui" },
      { path: "ui/dropdown-menu/dropdown-menu-sub.component.ts", type: "registry:ui" },
      { path: "ui/dropdown-menu/dropdown-menu-sub.component.html", type: "registry:ui" },
      { path: "ui/dropdown-menu/dropdown-menu.variants.ts", type: "registry:ui" },
      { path: "ui/dropdown-menu/dropdown-menu.icons.ts", type: "registry:ui" },
      { path: "ui/dropdown-menu/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/dropdown-menu" } },
  },
  {
    name: "context-menu",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/context-menu/context-menu.component.ts", type: "registry:ui" },
      { path: "ui/context-menu/context-menu.component.html", type: "registry:ui" },
      { path: "ui/context-menu/context-menu-selectable.component.ts", type: "registry:ui" },
      { path: "ui/context-menu/context-menu-sub.component.ts", type: "registry:ui" },
      { path: "ui/context-menu/context-menu-sub.component.html", type: "registry:ui" },
      { path: "ui/context-menu/context-menu.variants.ts", type: "registry:ui" },
      { path: "ui/context-menu/context-menu.icons.ts", type: "registry:ui" },
      { path: "ui/context-menu/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/context-menu" } },
  },
  {
    name: "menubar",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/menubar/menubar.component.ts", type: "registry:ui" },
      { path: "ui/menubar/menubar.component.html", type: "registry:ui" },
      { path: "ui/menubar/menubar-selectable.component.ts", type: "registry:ui" },
      { path: "ui/menubar/menubar-sub.component.ts", type: "registry:ui" },
      { path: "ui/menubar/menubar-sub.component.html", type: "registry:ui" },
      { path: "ui/menubar/menubar.variants.ts", type: "registry:ui" },
      { path: "ui/menubar/menubar.icons.ts", type: "registry:ui" },
      { path: "ui/menubar/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/menubar" } },
  },
  {
    name: "select",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/select/select.component.ts", type: "registry:ui" },
      { path: "ui/select/select.component.html", type: "registry:ui" },
      { path: "ui/select/select-trigger.component.html", type: "registry:ui" },
      { path: "ui/select/select-item.component.html", type: "registry:ui" },
      { path: "ui/select/select.variants.ts", type: "registry:ui" },
      { path: "ui/select/select.icons.ts", type: "registry:ui" },
      { path: "ui/select/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/select" } },
  },
  {
    name: "command",
    type: "registry:ui",
    files: [
      { path: "ui/command/command-dialog.component.ts", type: "registry:ui" },
      { path: "ui/command/command.component.html", type: "registry:ui" },
      { path: "ui/command/command.component.ts", type: "registry:ui" },
      { path: "ui/command/command.icons.ts", type: "registry:ui" },
      { path: "ui/command/command.score.ts", type: "registry:ui" },
      { path: "ui/command/command.service.ts", type: "registry:ui" },
      { path: "ui/command/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/command" } },
  },
  {
    name: "combobox",
    type: "registry:ui",
    dependencies: ["@angular/cdk"],
    registryDependencies: ["button", "input-group", "separator"],
    files: [
      { path: "ui/combobox/combobox-chip.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-chip.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-chips-input.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-chips-input.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-chips.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-chips.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-clear.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-clear.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-collection.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-collection.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-content.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-content.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-empty.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-empty.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-group.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-group.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-group.token.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-input.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-input.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-item.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-item.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-label.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-label.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-list.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-list.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-root.service.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-separator.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-separator.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-trigger.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-trigger.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox-value.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox-value.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox.component.html", type: "registry:ui" },
      { path: "ui/combobox/combobox.component.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox.filter.ts", type: "registry:ui" },
      { path: "ui/combobox/combobox.icons.ts", type: "registry:ui" },
      { path: "ui/combobox/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/combobox" } },
  },
  {
    name: "navigation-menu",
    type: "registry:ui",
    dependencies: ["@radix-ng/primitives"],
    files: [
      { path: "ui/navigation-menu/index.ts", type: "registry:ui" },
      { path: "ui/navigation-menu/navigation-menu.component.html", type: "registry:ui" },
      { path: "ui/navigation-menu/navigation-menu.component.ts", type: "registry:ui" },
      { path: "ui/navigation-menu/navigation-menu.icons.ts", type: "registry:ui" },
      { path: "ui/navigation-menu/navigation-menu.variants.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/navigation-menu" } },
  },
  {
    name: "sonner",
    type: "registry:ui",
    dependencies: ["ngx-sonner"],
    files: [
      { path: "ui/sonner/index.ts", type: "registry:ui" },
      { path: "ui/sonner/sonner.component.html", type: "registry:ui" },
      { path: "ui/sonner/sonner.component.ts", type: "registry:ui" },
      { path: "ui/sonner/sonner.icons.ts", type: "registry:ui" },
      { path: "ui/sonner/sonner.variants.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/sonner" } },
  },
  {
    name: "calendar",
    type: "registry:ui",
    files: [
      { path: "ui/calendar/calendar.component.html", type: "registry:ui" },
      { path: "ui/calendar/calendar.component.ts", type: "registry:ui" },
      { path: "ui/calendar/calendar.icons.ts", type: "registry:ui" },
      { path: "ui/calendar/calendar.utils.ts", type: "registry:ui" },
      { path: "ui/calendar/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/calendar" } },
  },
  {
    name: "direction",
    type: "registry:ui",
    dependencies: ["@angular/cdk"],
    files: [
      { path: "ui/direction/direction.component.ts", type: "registry:ui" },
      { path: "ui/direction/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/direction" } },
  },
  {
    name: "attachment",
    type: "registry:ui",
    files: [
      { path: "ui/attachment/attachment.component.html", type: "registry:ui" },
      { path: "ui/attachment/attachment.component.ts", type: "registry:ui" },
      { path: "ui/attachment/attachment.variants.ts", type: "registry:ui" },
      { path: "ui/attachment/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/attachment" } },
  },
  {
    name: "bubble",
    type: "registry:ui",
    files: [
      { path: "ui/bubble/bubble-content.component.html", type: "registry:ui" },
      { path: "ui/bubble/bubble-group.component.html", type: "registry:ui" },
      { path: "ui/bubble/bubble-reactions.component.html", type: "registry:ui" },
      { path: "ui/bubble/bubble.component.html", type: "registry:ui" },
      { path: "ui/bubble/bubble.component.ts", type: "registry:ui" },
      { path: "ui/bubble/bubble.variants.ts", type: "registry:ui" },
      { path: "ui/bubble/index.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/bubble" } },
  },
  {
    name: "marker",
    type: "registry:ui",
    files: [
      { path: "ui/marker/index.ts", type: "registry:ui" },
      { path: "ui/marker/marker.component.html", type: "registry:ui" },
      { path: "ui/marker/marker.component.ts", type: "registry:ui" },
      { path: "ui/marker/marker.variants.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/marker" } },
  },
  {
    name: "message",
    type: "registry:ui",
    registryDependencies: ["avatar", "bubble"],
    files: [
      { path: "ui/message/index.ts", type: "registry:ui" },
      { path: "ui/message/message.component.html", type: "registry:ui" },
      { path: "ui/message/message.component.ts", type: "registry:ui" },
      { path: "ui/message/message.variants.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/message" } },
  },
  {
    name: "message-scroller",
    type: "registry:ui",
    registryDependencies: ["button", "message"],
    files: [
      { path: "ui/message-scroller/index.ts", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller-button.component.html", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller-button.component.ts", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller-content.component.html", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller-content.component.ts", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller-item.component.html", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller-item.component.ts", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller-provider.component.ts", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller-viewport.component.html", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller-viewport.component.ts", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller.component.html", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller.component.ts", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller.icons.ts", type: "registry:ui" },
      { path: "ui/message-scroller/message-scroller.variants.ts", type: "registry:ui" },
    ],
    meta: { links: { docs: "https://forceui.public.prd.shared.perforce.com/docs/components/angular/message-scroller" } },
  },
]
